// Typed wrappers around auto-generated Wails Go bindings.
// The actual JS functions are generated by `wails dev` / `wails build` into
// frontend/wailsjs/go/app/WailsService.js. During pure frontend development
// these imports resolve at build time — they are not needed for `tsc --noEmit`
// if the declaration stubs exist; otherwise the `any` fallback keeps compiling.

import {
  LoadConfig,
  SaveConfig,
  Authenticate,
  FetchCourse,
  ResolveVideos,
  ResolveExercises,
  StartDownload,
  Cancel,
  SetQuality,
  SetOutputDir,
} from "../../wailsjs/go/app/WailsService";

// --- Types matching Go structs from app/wails_types.go ---

export interface ConfigResponse {
  token: string;
  quality: string;
  outputDir: string;
  courseUrl: string;
  found: boolean;
}

export interface SaveConfigRequest {
  token: string;
  quality: string;
  outputDir: string;
  courseUrl: string;
}

export interface AuthResponse {
  success: boolean;
  error?: string;
}

export interface CourseResponse {
  title: string;
  chapterCount: number;
  videoCount: number;
  hasExercises: boolean;
  chapters: ChapterResponse[];
  error?: string;
}

export interface ChapterResponse {
  title: string;
  slug: string;
  videos: VideoResponse[];
}

export interface VideoResponse {
  title: string;
  slug: string;
  duration: number;
  downloadUrl?: string;
}

export interface ResolveProgress {
  current: number;
  total: number;
  title: string;
  error?: string;
}

export interface DownloadProgressEvent {
  jobId: string;
  fileName: string;
  status: string;
  bytesDone: number;
  bytesTotal: number;
  error?: string;
}

export interface DownloadCompleteResponse {
  succeeded: number;
  failed: number;
  skipped: number;
  error?: string;
}

export interface DownloadStartResponse {
  totalJobs: number;
}

// --- Binding wrapper ---

function wrapError(operation: string, err: unknown): Error {
  if (err instanceof Error) {
    return new Error(`${operation}: ${err.message}`);
  }
  return new Error(`${operation}: ${String(err)}`);
}

export const wailsBinding = {
  loadConfig(): Promise<ConfigResponse> {
    return LoadConfig().catch((err: unknown) => {
      throw wrapError("LoadConfig", err);
    });
  },

  saveConfig(req: SaveConfigRequest): Promise<void> {
    return SaveConfig(req).catch((err: unknown) => {
      throw wrapError("SaveConfig", err);
    });
  },

  authenticate(token: string): Promise<AuthResponse> {
    return Authenticate(token).catch((err: unknown) => {
      throw wrapError("Authenticate", err);
    });
  },

  fetchCourse(courseURL: string): Promise<CourseResponse> {
    return FetchCourse(courseURL).catch((err: unknown) => {
      throw wrapError("FetchCourse", err);
    });
  },

  resolveVideos(): Promise<void> {
    return ResolveVideos().catch((err: unknown) => {
      throw wrapError("ResolveVideos", err);
    });
  },

  resolveExercises(): Promise<void> {
    return ResolveExercises().catch((err: unknown) => {
      throw wrapError("ResolveExercises", err);
    });
  },

  startDownload(): Promise<void> {
    return StartDownload().catch((err: unknown) => {
      throw wrapError("StartDownload", err);
    });
  },

  cancel(): Promise<void> {
    return Cancel().catch((err: unknown) => {
      throw wrapError("Cancel", err);
    });
  },

  setQuality(quality: string): Promise<void> {
    return SetQuality(quality).catch((err: unknown) => {
      throw wrapError("SetQuality", err);
    });
  },

  setOutputDir(dir: string): Promise<void> {
    return SetOutputDir(dir).catch((err: unknown) => {
      throw wrapError("SetOutputDir", err);
    });
  },
};
