// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['app']['WailsService']['Authenticate'](arg1);
}

export function Cancel() {
  return window['go']['app']['WailsService']['Cancel']();
}

export function FetchCourse(arg1) {
  return window['go']['app']['WailsService']['FetchCourse'](arg1);
}

export function LoadConfig() {
  return window['go']['app']['WailsService']['LoadConfig']();
}

export function ResolveExercises() {
  return window['go']['app']['WailsService']['ResolveExercises']();
}

export function ResolveVideos() {
  return window['go']['app']['WailsService']['ResolveVideos']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['WailsService']['SaveConfig'](arg1);
}

export function SetOutputDir(arg1) {
  return window['go']['app']['WailsService']['SetOutputDir'](arg1);
}

export function SetQuality(arg1) {
  return window['go']['app']['WailsService']['SetQuality'](arg1);
}

export function StartDownload() {
  return window['go']['app']['WailsService']['StartDownload']();
}
