// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Authenticate(arg1:string):Promise<app.AuthResponse>;

export function Cancel():Promise<void>;

export function FetchCourse(arg1:string):Promise<app.CourseResponse>;

export function LoadConfig():Promise<app.ConfigResponse>;

export function ResolveExercises():Promise<void>;

export function ResolveVideos():Promise<void>;

export function SaveConfig(arg1:app.SaveConfigRequest):Promise<void>;

export function SetOutputDir(arg1:string):Promise<void>;

export function SetQuality(arg1:string):Promise<void>;

export function StartDownload():Promise<void>;
